cmdb/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'cmdb'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('storage_list/', StorageListView.as_view(), name='storagelist'),
    path('gpu_list/', GPUListView.as_view(), name='gpulist'),
    re_path('storage_del/(?P<pk>[0-9]+)?/', StorageDeleteView.as_view(), name='storagedel'),
    re_path('gpu_del/(?P<pk>[0-9]+)?/', GPUDeleteView.as_view(), name='gpudel'),
    re_path('storage_modify/(?P<pk>[0-9]+)?/', StorageUpdateView.as_view(), name='storagemodify'),
    re_path('gpu_modify/(?P<pk>[0-9]+)?/', GPUUpdateView.as_view(), name='gpumodify'),
    path('overview/', AssetsOverView.as_view(), name='overview'),
    path('update_host_info/', update_host_info, name='update-host-info'),
]

minefieldplatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmdb.urls', namespace='cmdb')),
    path('task/', include('task.urls', namespace='task')),
]

task/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'task'

urlpatterns = [
    path('add/', TaskAddView.as_view(), name='task_add'),
    path('get_playbook/', get_playbook, name='get_playbook'),
    path('list/', TaskListView.as_view(), name='task_list'),
    re_path('detail/(?P<pk>[0-9]+)?/', TaskDetailView.as_view(), name='task_detail'),
    re_path('cancel/(?P<pk>[0-9]+)?/', TaskCancelView.as_view(), name='task_cancel'),
    path('get_task_result/', get_task_result, name='get_task_result'),
    re_path('publish/(?P<pk>[0-9]+)?/', task_publish, name='task_publish'),
]

task/models.py
from django.db import models


class Task(models.Model):
    STATUS = (
        (0, '未发布'),
        (1, '已发布'),
        (2, '已取消'),
    )
    name = models.CharField(max_length=100, verbose_name='任务名')
    dest_hosts = models.TextField(verbose_name='目标主机')
    content = models.TextField(verbose_name='更新内容', null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    status = models.IntegerField(default=0, choices=STATUS)
    result = models.TextField(null=True, verbose_name='执行结果')

    class Meta:
        verbose_name = '任务系统'
        verbose_name_plural = '任务系统'

    def __str__(self):
        return self.name

task/views.py
import os
from django.shortcuts import render, reverse, redirect
from django.views.decorators.http import require_POST, require_GET
from django.views.generic import View, ListView, DetailView
from minefieldplatform.settings import BASE_DIR
from django.http import JsonResponse
from django.template import loader
from .models import Task
from pure_pagination import PaginationMixin
from django.db.models import Q
from django_redis import get_redis_connection
from .task import task_execute

redis_cli = get_redis_connection('default')


class TaskAddView(View):
    @staticmethod
    def get(request):
        return render(request, 'task/generaltask_add.html')

    @staticmethod
    def post(request):
        host = request.POST.get('host')
        content = request.POST.get('content')
        name = request.POST.get('name')

        task = Task()
        task.name = name
        task.content = content
        task.dest_hosts = host
        task.save()
        return JsonResponse({'code': 0, 'msg': '任务创建成功'})


class TaskListView(PaginationMixin, ListView):
    """
    任务列表
    """
    template_name = 'task/task_list.html'
    model = Task
    paginate_by = 10
    keyword = None

    def get_keyword(self):
        self.keyword = self.request.GET.get('keyword')
        return self.keyword

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by("-created_at")
        keyword = self.get_keyword()
        if keyword:
            queryset = queryset.filter(Q(name__icontains=keyword) | Q(dest_hosts__icontains=keyword) |
                                       Q(content__icontains=keyword) | Q(created_at__month=keyword) |
                                       Q(created_at__day=keyword))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['keyword'] = self.keyword
        return context


class TaskCancelView(View):

    @staticmethod
    def get(request, pk):
        task = Task.objects.filter(id=pk).get()
        task.status = 2
        task.save()
        # return reverse('task:task_list')
        # response = HttpResponse('取消成功')
        print(pk)
        return redirect(reverse('task:task_detail', args=[pk]))

    @property
    def get_success_url(self):
        return reverse('task:task_list')


class TaskDetailView(DetailView):
    """
    任务详情页
    """
    template_name = 'task/task_detail.html'
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prev'] = self.request.GET.get('prev')
        return context


@require_POST
def get_playbook(request):
    host = request.POST.get('host', '')
    content = request.POST.get('content', '')
    if content:
        with open(os.path.join(BASE_DIR, 'tmp', 'tmp_playbook.yml'), 'w') as f:
            f.write(content)
        with open(os.path.join(BASE_DIR, 'tmp', 'tmp_playbook.yml'), 'r') as f:
            content = ''
            for line in f:
                if line.startswith('- hosts'):
                    content += '- hosts: \'{}\'\n'.format(host)
                else:
                    content += line
    else:
        content = loader.render_to_string(
            'task/playbook_demo.yml.template', {'dest_hosts': host})
    return JsonResponse({'code': 0, 'msg': '获取Playbook demo成功!', 'content': content})


@require_POST
def task_publish(request, pk):
    """
    发布任务
    :param request:
    :param pk
    :return:
    """
    # 发布任务  状态流转
    # historic_task = HistoricTask.objects.filter(id=pk).get()
    # historic_task.status = 3
    # historic_task.publisher = request.user
    # historic_task.publish_at = timezone.now()
    # historic_task.save()
    # 任务执行
    # task = Task.objects.get(id=historic_task.task_id)
    # task.dest_hosts.set([host.id for host in historic_task.dest_hosts.all()])
    # task.content = historic_task.content
    # 同步执行
    task_execute(pk)
    # task.save()
    return JsonResponse({'code': 0, 'msg': '已将任务放到后台执行，请稍后！'})


@require_GET
def get_task_result(request):
    """
    发布配置文件结果
    :param request:
    :return:
    """
    task_id = request.GET.get('task_id')
    redis_key_prefix = 'ark::task'
    data = redis_cli.get('{}::{}'.format(redis_key_prefix, task_id))
    if not data:
        data = "任务开始执行，请稍作等待！"
    else:
        data = str(data, encoding='utf8')
    return JsonResponse({'code': 0, 'data': data})

templates/task/generaltask_add.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/select2/select2.css' %}"/>
    <style>
        #editor {
            width: 100%;
            height: 300px;
        }

        .host-link {
            margin-top: 10px
        }

        .host-link .host-tags {
            margin-right: 5px;
            cursor: pointer
        }
    </style>
{% endblock %}
{% block title %}
    添加通用任务
{% endblock %}
{% block page-title %}
    添加通用任务
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">添加通用任务</h3>
                </div>
                <div class="panel-body">
                    <form method="post" class="form-horizontal">
                        <div class="form-group web">
                            <label class="col-sm-2 control-label">目标机器：</label>
                            <div class="col-sm-6">
                                <input placeholder="填入IP地址，用英文逗号分隔..." type="text" class="form-control"
                                       id="dest_hosts" name="dest_hosts" autocomplete="off">
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">脚本：</label>
                            <div class="col-sm-6">
                                <div id="editor"></div>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">任务概述：</label>
                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="name" name="name" autocomplete="off">
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn-submit" type="button">保存</button>
                                <input class="btn btn-white" type="reset" value="取消">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'ace/src/ace.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'ace/src/theme-chrome.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'ace/src/mode-nginx.js' %}"></script>
    <script src="{% static 'ace/src/mode-yaml.js' %}"></script>
    <script src="{% static 'ace/src/ext-language_tools.js' %}"></script>
    <script src="{% static 'assets/select2/select2.min.js' %}" type="text/javascript"></script>
    <script>
        jQuery(".select2").select2({
            width: '100%'
        });
    </script>
    <script>
        var editor = ace.edit("editor");
        //字体大小
        editor.setTheme('ace/theme/chrome');
        editor.session.setMode('ace/mode/yaml');
        editor.setFontSize(18);
        //设置只读（true时只读，用于展示代码）
        editor.setReadOnly(false);
        //自动换行,设置为off关闭
        editor.setOption("wrap", "free");
        //启用提示菜单
        editor.setOptions({
            enableBasicAutocompletion: true,
            enableSnippets: true,
            enableLiveAutocompletion: true,
        });
    </script>
    <script>
        //获取playbookdemo
        function get_playbook_demo() {
            // 第一步：获取到当前input里面的主机id，并存到列表中
            var host = document.getElementById('dest_hosts').value;
            // 第二步：拿到当前脚本内容
            var content = editor.getValue();
            // 第三步：将当前获取的主机ip以及脚本内容传到后端进行处理
            $.ajax({
                type: 'POST',
                'url': '/task/get_playbook/',
                data: {'host': host, 'content': content},
                success: function (result) {
                    console.log(result)
                    // 第四步：请求成功之后，将后端拼接好的playbook写入到我们到脚本框中
                    if (result['code'] === 0) {
                        var content = result['content'];
                        editor.setValue(content);
                    }
                }
            })
        }
        //监听主机变化事件
        $('#dest_hosts').on('change', function () {
            get_playbook_demo();
        });

        //监听提交按钮点击事件
        $('.btn-submit').click(function () {
            var host = document.getElementById('dest_hosts').value;
            var content = editor.getValue();
            var name = $('#name').val();
            if (host.length === 0 || content === '' || name === '') {
                swal({
                    title: '警告',
                    text: '表单不能为空，请填充完整表单!',
                    type: 'warning',
                });
                return false
            }
            $.ajax({
                type: 'POST',
                url: '/task/add/',
                data: {host: host, content: content, name: name},
                success: function (result) {
                    if (result['code'] === 0) {
                        window.location.href = '/task/list/';
                    }
                }
            })
        })
    </script>
    <script>
        $('.task').addClass('active');
        $('.task .general-task-add').addClass('active');
    </script>
{% endblock %}

templates/task/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    任务详情
{% endblock %}
{% block css %}

{% endblock %}
{% block page-title %}
    任务详情
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-lg-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">查看任务详情</h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <td class="text-right">任务概述</td>
                                <td>{{ object.name }}</td>
                            </tr>
                            <tr>
                                <td class="text-right">目标机器</td>
                                <td>{{ object.dest_hosts }}</td>
                            </tr>
                            <tr>
                                <td class="text-right">提交时间</td>
                                <td>{{ object.created_at }}</td>
                            </tr>
                            <tr>
                                <td class="text-right">状态</td>
                                <td><label
                                        class="label label-status
                                        {% if object.status == 0 %}
                                        label-default
                                        {% elif object.status == 1 %}
                                        label-success
                                        {% elif object.status == 2 %}
                                        label-danger
                                        {% endif %}">{{ object.get_status_display }}
                                </label>
                                </td>
                            </tr>
                            <tr>
                                <td class="text-right">动作</td>
                                <td class="task-action">
                                    {% if object.status == 2 %}
                                        <a href="{% url 'task:task_list' %}" class="btn btn-primary btn-xs">任务列表</a>
                                    {% elif object.status == 1 %}
                                        <a href="{% url 'task:task_list' %}" class="btn btn-primary btn-xs">任务列表</a>
                                        <a href="javascript:void(0)"
                                           class="btn btn-warning btn-xs btn-result">查看结果</a>
                                    {% elif object.status == 0 %}
                                        <a href="{% url 'task:task_cancel' object.id %}" class="btn btn-danger btn-xs">取消任务</a>
                                        <button class="btn btn-info btn-xs btn-publish">发布任务</button>
                                    {% endif %}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-7">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">配置文件(或Playbook)的内容</h3>
                </div>
                <div class="panel-body" style="height: 555px">
                    <pre style="height:500px;overflow: scroll">{{ object.content|safe }}</pre>
                </div>
            </div>
        </div>
    </div>

    <!--执行结果模态窗-->
    <div class="modal inmodal fade" id="task_result" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span
                            class="sr-only">Close</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <pre id="content"></pre>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        // 点击发布按钮
        // 1、将当前任务提交到后端执行， 2、执行成功之后，将执行结果通过莫泰窗展示来
        $('.btn-publish').click(function () {
            $.ajax({
                type: "POST",
                url: "{% url 'task:task_publish' object.id %}",
                data: {},
                success: function (result) {
                    console.log(result)
                    if (result['code'] === 0) {
                        var modal = $('#task_result');
                        modal.modal("show");
                        get_task_result(modal, '{{ object.id }}');
                    }
                }
            })
        });

        // 获取任务的执行结果
        function get_task_result(modal, task_id) {
            $.ajax({
                type: "GET",
                url: "/task/get_task_result/?task_id=" + task_id,
                success: function (result) {
                    modal.find('.modal-body #content').text(result['data']);
                }
            })
        }

        //点击查看结果按钮
        $('.task-action').on('click', '.btn-result', function () {
            var modal = $('#task_result');
            modal.modal("show");
            get_task_result(modal, '{{ object.id }}');
        });
    </script>
{% endblock %}

templates/task/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

{% endblock %}
{% block title %}
任务列表
{% endblock %}
{% block page-title %}
任务列表
{% endblock %}
{% block page-content %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">查看任务列表</h3>
            </div>
            <div class="panel-body">
                <div class="row" style="margin-bottom: 5px">
                    <div class="col-md-2" style="float: right">
                        <form class="form-horizontal" role="form">
                            <div class="input-group">
                                <input type="text" id="keyword" name="keyword" class="form-control"
                                    value="{{ keyword|default_if_none:'' }}" placeholder="关键字">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-effect-ripple btn-primary">搜索</button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table class="table table-bordered" style="table-layout:fixed;width: 100%">
                            <thead>
                                <tr>
                                    <th style="width: 15%;text-align: center">任务概述</th>
                                    <th style="width: 30%;text-align: center">目标机器</th>
                                    <th style="width: 10%;text-align: center">提交时间</th>
                                    <th style="width: 10%;text-align: center">任务详情</th>
                                    <th style="width: 10%;text-align: center">任务状态</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for task in object_list %}
                                <tr>
                                    <td style="word-wrap: break-word;width: 25%;text-align: center">{{ task.name }}</td>
                                    <td style="word-wrap: break-word;width: 50%;text-align: center">
                                        {{ task.dest_hosts }}</td>
                                    <td style="word-wrap: break-word;width: 10%;text-align: center">
                                        {{ task.created_at }}</td>
                                    <td style="word-wrap: break-word;width: 5%;text-align: center">
                                        <a href="{% url 'task:task_detail' task.id %}?prev=tasks"
                                            style="color: rgba(0,170,255,0.74)">查看</a>
                                    </td>
                                    <td style="word-wrap: break-word;width: 5%;text-align: center">
                                        <label class="label
                                                    {% if task.status == 0 %}
                                                    label-default
                                                    {% elif task.status == 1 %}
                                                    label-success
                                                    {% elif task.status == 2 %}
                                                    label-danger
                                                    {% endif %}">{{ task.get_status_display }}
                                        </label>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <p style="margin-top: 10px"> 显示 [{{ page_obj.paginator.count }}] 条数据中的 第
                            [{{ page_obj.start_index }}] 至 [{{ page_obj.end_index }}] 的数据</p>
                    </div>
                    <div class="col-md-8">
                        {% if page_obj.paginator.num_pages > 1 %}
                        {% include '_paginator.html' %}
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $('.task').addClass('active');
    $('.task .tasks').addClass('active');
</script>
{% endblock %}