cmdb/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'cmdb'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('storage_list/', StorageListView.as_view(), name='storagelist'),
    path('gpu_list/', GPUListView.as_view(), name='gpulist'),
    re_path('storage_del/(?P<pk>[0-9]+)?/', StorageDeleteView.as_view(), name='storagedel'),
    re_path('gpu_del/(?P<pk>[0-9]+)?/', GPUDeleteView.as_view(), name='gpudel'),
    re_path('storage_modify/(?P<pk>[0-9]+)?/', StorageUpdateView.as_view(), name='storagemodify'),
    re_path('gpu_modify/(?P<pk>[0-9]+)?/', GPUUpdateView.as_view(), name='gpumodify'),
    path('overview/', AssetsOverView.as_view(), name='overview'),
    path('update_host_info/', update_host_info, name='update-host-info'),
]

minefieldplatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmdb.urls', namespace='cmdb')),
    path('task/', include('task.urls', namespace='task')),
]

cmdb/models.py
from django.db import models


class GPUMachine(models.Model):
    ip = models.GenericIPAddressField(verbose_name='gpu机器ip地址')
    cpu_cores = models.IntegerField(
        verbose_name='cpu核心数，单位：核', null=True, blank=True)
    total_memory = models.IntegerField(
        verbose_name='内存大小，单位：G', null=True, blank=True)
    gpu_numbers = models.IntegerField(
        verbose_name='GPU数量，单位：个', null=True, blank=True)
    mount_with = models.CharField(
        verbose_name='挂载的存储机器ip', null=True, blank=True, max_length=200)
    area = models.CharField(verbose_name='所属矿场',
                            max_length=10, null=True, blank=True)
    node_status = models.CharField(
        verbose_name='运行状态', max_length=10, null=True, blank=True)

    class Meta:
        verbose_name = 'GPU机器信息'

    def __str__(self):
        return self.ip


class StorageMachine(models.Model):
    ip = models.GenericIPAddressField(verbose_name='存储机器ip地址')
    cpu_cores = models.IntegerField(
        verbose_name='cpu核心数，单位：核', null=True, blank=True)
    total_memory = models.IntegerField(
        verbose_name='内存大小，单位：G', null=True, blank=True)
    disk = models.IntegerField(verbose_name='硬盘数量，单位：块', null=True, blank=True)
    area = models.CharField(verbose_name='所属矿场',
                            max_length=10, null=True, blank=True)
    node_status = models.CharField(
        verbose_name='机器运行状态', max_length=10, null=True, blank=True)
    current_file = models.IntegerField(
        verbose_name='当前P盘文件号', blank=True, default=0)
    capacity = models.DecimalField(
        verbose_name='可提供算力', blank=True, default=0, decimal_places=3, max_digits=20)

    class Meta:
        verbose_name = '存储机器信息'

    def __str__(self):
        return self.ip

cmdb/views.py
from django.db.models import Q
from django.shortcuts import render, reverse
from django.views.generic import View, ListView, DeleteView, UpdateView
from cmdb.models import StorageMachine, GPUMachine
from pure_pagination import PaginationMixin
from .summary import assets_overview, index_overview
from django.views.decorators.http import require_GET
from django.http import HttpResponse, JsonResponse
from .tasks import update_hosts_from_minefield


class IndexView(View):
    @staticmethod
    def get(request):
        overview = index_overview()
        context = {
            'overview': overview,
        }
        return render(request, 'index.html', context=context)

    @staticmethod
    def post(request):
        print("hello")
        return render(request, 'index.html')


class StorageListView(PaginationMixin, ListView):
    template_name = "cmdb/storagelist.html"
    model = StorageMachine
    paginate_by = 10
    keyword = ""

    def get_keyword(self):
        self.keyword = self.request.GET.get('keyword')
        return self.keyword

    # 数据过滤
    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.get_keyword()
        if keyword:
            queryset = queryset.filter(Q(ip__icontains=keyword) |
                                       Q(area__contains=keyword) |
                                       Q(node_status__contains=keyword))

        return queryset

    # 搜索关键字传给前端
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['keyword'] = self.keyword
        return context


class GPUListView(PaginationMixin, ListView):
    template_name = "cmdb/gpulist.html"
    model = GPUMachine
    paginate_by = 10
    keyword = ""

    def get_keyword(self):
        self.keyword = self.request.GET.get('keyword')
        return self.keyword

    # 数据过滤
    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.get_keyword()
        if keyword:
            queryset = queryset.filter(Q(ip__icontains=keyword) |
                                       Q(area__contains=keyword) |
                                       Q(node_status__contains=keyword) |
                                       Q(mount_with__icontains=keyword))

        return queryset

    # 搜索关键字传给前端
    def get_context_data(self, **kwargs):
        context = super(GPUListView, self).get_context_data(**kwargs)
        context['keyword'] = self.keyword
        return context


class StorageDeleteView(DeleteView):
    template_name = 'cmdb/storage_delete_confirm.html'
    model = StorageMachine

    def get_success_url(self):
        return reverse('cmdb:storagelist')


class GPUDeleteView(DeleteView):
    template_name = 'cmdb/gpu_delete_confirm.html'
    model = GPUMachine

    def get_success_url(self):
        return reverse('cmdb:gpulist')


class StorageUpdateView(UpdateView):
    template_name = "cmdb/storageform.html"
    model = StorageMachine
    fields = ('ip', 'cpu_cores', 'total_memory', 'disk', 'area', 'node_status')

    def get_success_url(self):
        return reverse('cmdb:storagelist')


class GPUUpdateView(UpdateView):
    template_name = "cmdb/gpuform.html"
    model = GPUMachine
    fields = ('ip', 'cpu_cores', 'total_memory',
              'gpu_numbers', 'area', 'node_status')

    def get_success_url(self):
        return reverse('cmdb:gpulist')


class AssetsOverView(View):
    @staticmethod
    def get(request):
        overview = assets_overview()
        context = {
            'overview': overview,
        }
        return render(request, 'cmdb/assets_overview.html', context=context)


@require_GET
def update_host_info(request):
    """
    更新主机信息
    :param request:
    :return:
    """
    # update_hosts_from_minefield.delay()
    update_hosts_from_minefield()
    return HttpResponse('任务已提交到后台，请稍等片刻！')

templates/cmdb/gpu_delete_confirm.html
{% extends 'base.html' %}
{% block css %}

{% endblock %}
{% block title %}
    删除GPU机器
{% endblock %}
{% block page-title %}
    删除GPU机器
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <h3>确定删除 {{ object.ip }} ?</h3>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-danger" value="确定">
                            <input type="button" class="btn btn-info"  value="取消" onclick="history.go(-1);"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}

{% endblock %}

templates/cmdb/gpuform.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    GPU机器修改
{% endblock %}
{% block page-title %}
    GPU机器修改
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">正在修改 {{ object.ip }}</h3></div>
                <div class="panel-body">
                    <div class=" form">
                        <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action=""
                              novalidate="novalidate">
                            <div class="form-group ">
                                <label for="ip" class="control-label col-lg-2">IP *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="ip"
                                           value="{% if object %}{{ object.ip }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cpu_cores" class="control-label col-lg-2">CPU核数 *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="cpu_cores"
                                           value="{% if object %}{{ object.cpu_cores }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="total_memory" class="control-label col-lg-2">内存大小(GB) *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="total_memory"
                                           value="{% if object %}{{ object.total_memory }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="gpu_numbers" class="control-label col-lg-2">GPU数量 *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="gpu_numbers"
                                           value="{% if object %}{{ object.gpu_numbers }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="area" class="control-label col-lg-2">所属矿场 *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="area"
                                           value="{% if object %}{{ object.area }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="node_status" class="control-label col-lg-2">节点状态 *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="node_status"
                                           value="{% if object %}{{ object.node_status }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-success" type="submit">确定</button>
                                    <input type="button" class="btn btn-default" value="取消" onclick="history.go(-1);"/>
                                </div>
                            </div>
                        </form>
                    </div> <!-- .form -->
                </div> <!-- panel-body -->
            </div> <!-- panel -->
        </div> <!-- col -->
    </div> <!-- End row -->
{% endblock %}

templates/cmdb/gpulist.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link href="https://cdn.bootcss.com/bootstrap-table/1.12.1/bootstrap-table.min.css" rel="stylesheet">
    <link href="static/assets/sweet-alert/sweet-alert.min.css">
    <style>
        .tag-title {
            line-height: 30px;
            padding: 5px 15px;
            border: 1px solid #e7eaec;
            border-bottom: none;
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;
        }

        .tag-title a {
            float: right
        }

        .list-group-item:first-child {
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .fixed-table-container {
            height: auto !important;
        }

        .transferBox {
            height: 100%;
            border: 1px solid #beb8b8;
            border-radius: 2px;
            overflow-y: scroll
        }

        .error-msg {
            color: red
        }
    </style>
{% endblock %}
{% block title %}
    GPU机器列表
{% endblock %}
{% block page-title %}
    GPU机器列表
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-lg-12">
            <ul class="nav nav-tabs">
                <li class="">
                    <a href="{% url 'cmdb:storagelist' %}" aria-expanded="true">
                        <span class="visible-xs"><i class="fa fa-server"></i></span>
                        <span class="hidden-xs">存储机器</span>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'cmdb:gpulist' %}" aria-expanded="false">
                        <span class="visible-xs"><i class="fa fa-envelope-o"></i></span>
                        <span class="hidden-xs">GPU机器</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="hosts">
                    <div class="row" style="margin-bottom: 5px">
                        <div class="col-md-1">
                            <button id="update-host-info" class="btn btn-primary btn-sm" title="同步矿场资产到管理平台">
                                同步资产
                            </button>
                        </div>
                        <div class="col-md-2" style="float: right">
                            <form class="form-horizontal" role="form">
                                <div class="input-group">
                                    <input type="text" id="keyword" name="keyword"
                                           value="{{ keyword|default_if_none:'' }}" class="form-control"
                                           placeholder="关键字">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-effect-ripple btn-primary">搜索</button>
                                        </span>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <table class="table table-bordered" style="width: 100%">
                                <thead>
                                <tr>
                                    <th class="text-center">IP</th>
                                    <th class="text-center">CPU核数</th>
                                    <th class="text-center">内存大小(GB)</th>
                                    <th class="text-center">GPU数量</th>
                                    <th class="text-center">所属矿场</th>
                                    <th class="text-center">节点状态</th>
                                    <th class="text-center">挂载机器</th>
                                    <th class="text-center">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for host in object_list %}
                                    <tr class="{{ host.id }}">
                                        <td class="text-center">{{ host.ip }}</td>
                                        <td class="text-center">{{ host.cpu_cores }}</td>
                                        <td class="text-center">{{ host.total_memory }}</td>
                                        <td class="text-center">{{ host.gpu_numbers }}</td>
                                        <td class="text-center">{{ host.area }}</td>
                                        <td class="text-center">{{ host.node_status }}</td>
                                        <td class="text-center">{{ host.mount_with }}</td>
                                        <td class="actions text-center">
                                            <a href="{% url 'cmdb:gpumodify' host.id %}"
                                               class="btn btn-primary btn-xs">修改</a>
                                            <a href="{% url 'cmdb:gpudel' host.id %}"
                                               class="btn btn-danger btn-xs">删除</a>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="15" class="text-center">没有主机……</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div class="row">
                                <div class="col-md-4">
                                    <p style="margin-top: 10px"> 显示 [{{ page_obj.paginator.count }}] 条数据中的 第
                                        [{{ page_obj.start_index }}] 至 [{{ page_obj.end_index }}] 的数据</p>
                                </div>
                                <div class="col-md-8">
                                    {% if page_obj.paginator.num_pages > 1 %}
                                        {% include '_paginator.html' %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="https://cdn.bootcss.com/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-table/1.12.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="/static/assets/sweet-alert/sweet-alert.min.js"></script>
    <script>
        $(function () {
            $('#update-host-info').click(function () {
                $.get("/update_host_info/", function (data) {
                    console.log(data)
                    alert(data)
                });
            })
        })
    </script>
    <script>
        $('.cmdb').addClass('active');
        $('.cmdb .assets').addClass('active');
    </script>
{% endblock %}

templates/cmdb/storage_delete_confirm.html
{% extends 'base.html' %}
{% block css %}

{% endblock %}
{% block title %}
    删除存储机器
{% endblock %}
{% block page-title %}
    删除存储机器
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <h3>确定删除 {{ object.ip }} ?</h3>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-danger" value="确定">
                            <input type="button" class="btn btn-info"  value="取消" onclick="history.go(-1);"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}

{% endblock %}

templates/cmdb/storageform.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    存储机器修改
{% endblock %}
{% block page-title %}
    存储机器修改
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">正在修改 {{ object.ip }}</h3></div>
                <div class="panel-body">
                    <div class=" form">
                        <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action=""
                              novalidate="novalidate">
                            <div class="form-group ">
                                <label for="ip" class="control-label col-lg-2">IP *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="ip"
                                           value="{% if object %}{{ object.ip }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cpu_cores" class="control-label col-lg-2">CPU核数 *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="cpu_cores"
                                           value="{% if object %}{{ object.cpu_cores }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="total_memory" class="control-label col-lg-2">内存大小(GB) *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="total_memory"
                                           value="{% if object %}{{ object.total_memory }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="disk" class="control-label col-lg-2">硬盘容量(TB) *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="disk"
                                           value="{% if object %}{{ object.disk }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="area" class="control-label col-lg-2">所属矿场 *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="area"
                                           value="{% if object %}{{ object.area }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="node_status" class="control-label col-lg-2">节点状态 *</label>
                                <div class="col-lg-4">
                                    <input class=" form-control" name="node_status"
                                           value="{% if object %}{{ object.node_status }}{% endif %}" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-success" type="submit">确定</button>
                                    <input type="button" class="btn btn-default" value="取消" onclick="history.go(-1);"/>
                                </div>
                            </div>
                        </form>
                    </div> <!-- .form -->
                </div> <!-- panel-body -->
            </div> <!-- panel -->
        </div> <!-- col -->
    </div> <!-- End row -->
{% endblock %}

templates/cmdb/storagelist.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link href="https://cdn.bootcss.com/bootstrap-table/1.12.1/bootstrap-table.min.css" rel="stylesheet">
    <link href="static/assets/sweet-alert/sweet-alert.min.css">
    <style>
        .tag-title {
            line-height: 30px;
            padding: 5px 15px;
            border: 1px solid #e7eaec;
            border-bottom: none;
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;
        }

        .tag-title a {
            float: right
        }

        .list-group-item:first-child {
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .fixed-table-container {
            height: auto !important;
        }

        .transferBox {
            height: 100%;
            border: 1px solid #beb8b8;
            border-radius: 2px;
            overflow-y: scroll
        }

        .error-msg {
            color: red
        }
    </style>
{% endblock %}
{% block title %}
    存储机器列表
{% endblock %}
{% block page-title %}
    存储机器列表
{% endblock %}
{% block page-content %}
    <div class="row">
        <div class="col-lg-12">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="{% url 'cmdb:storagelist' %}" aria-expanded="true">
                        <span class="visible-xs"><i class="fa fa-server"></i></span>
                        <span class="hidden-xs">存储机器</span>
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'cmdb:gpulist' %}" aria-expanded="false">
                        <span class="visible-xs"><i class="fa fa-envelope-o"></i></span>
                        <span class="hidden-xs">GPU机器</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="hosts">
                    <div class="row" style="margin-bottom: 5px">
                        <div class="col-md-1">
                            <button id="update-host-info" class="btn btn-primary btn-sm" title="同步矿场资产到管理平台">
                                同步资产
                            </button>
                        </div>
                        <div class="col-md-2" style="float: right">
                            <form class="form-horizontal" role="form">
                                <div class="input-group">
                                    <input type="text" id="keyword" name="keyword"
                                           value="{{ keyword|default_if_none:'' }}" class="form-control"
                                           placeholder="关键字">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-effect-ripple btn-primary">搜索</button>
                                        </span>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <table class="table table-bordered" style="width: 100%">
                                <thead>
                                <tr>
                                    <th class="text-center">IP</th>
                                    <th class="text-center">CPU核数</th>
                                    <th class="text-center">内存大小(GB)</th>
                                    <th class="text-center">硬盘容量(TB)</th>
                                    <th class="text-center">所属矿场</th>
                                    <th class="text-center">节点状态</th>
                                    <th class="text-center">当前写入文件编号</th>
                                    <th class="text-center">可提供算力(TB)</th>
                                    <th class="text-center">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for host in object_list %}
                                    <tr class="{{ host.id }}">
                                        <td class="text-center">{{ host.ip }}</td>
                                        <td class="text-center">{{ host.cpu_cores }}</td>
                                        <td class="text-center">{{ host.total_memory }}</td>
                                        <td class="text-center">{{ host.disk }}</td>
                                        <td class="text-center">{{ host.area }}</td>
                                        <td class="text-center">{{ host.node_status }}</td>
                                        <td class="text-center">{{ host.current_file }}</td>
                                        <td class="text-center">{{ host.capacity }}</td>
                                        <td class="actions text-center">
                                            <a href="{% url 'cmdb:storagemodify' host.id %}"
                                               class="btn btn-primary btn-xs">修改</a>
                                            <a href="{% url 'cmdb:storagedel' host.id %}"
                                               class="btn btn-danger btn-xs">删除</a>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="15" class="text-center">没有主机……</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div class="row">
                                <div class="col-md-4">
                                    <p style="margin-top: 10px"> 显示 [{{ page_obj.paginator.count }}] 条数据中的 第
                                        [{{ page_obj.start_index }}] 至 [{{ page_obj.end_index }}] 的数据</p>
                                </div>
                                <div class="col-md-8">
                                    {% if page_obj.paginator.num_pages > 1 %}
                                        {% include '_paginator.html' %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="https://cdn.bootcss.com/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-table/1.12.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="/static/assets/sweet-alert/sweet-alert.min.js"></script>
    <script>
        $(function () {
            $('#update-host-info').click(function () {
                $.get("/update_host_info/", function (data) {
                    console.log(data)
                    alert(data)
                });
            })
        })
    </script>
    <script>
        $('.cmdb').addClass('active');
        $('.cmdb .assets').addClass('active');
    </script>
{% endblock %}