cmdb/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'cmdb'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('storage_list/', StorageListView.as_view(), name='storagelist'),
    path('gpu_list/', GPUListView.as_view(), name='gpulist'),
    re_path('storage_del/(?P<pk>[0-9]+)?/', StorageDeleteView.as_view(), name='storagedel'),
    re_path('gpu_del/(?P<pk>[0-9]+)?/', GPUDeleteView.as_view(), name='gpudel'),
    re_path('storage_modify/(?P<pk>[0-9]+)?/', StorageUpdateView.as_view(), name='storagemodify'),
    re_path('gpu_modify/(?P<pk>[0-9]+)?/', GPUUpdateView.as_view(), name='gpumodify'),
    path('overview/', AssetsOverView.as_view(), name='overview'),
    path('update_host_info/', update_host_info, name='update-host-info'),
]

minefieldplatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmdb.urls', namespace='cmdb')),
    path('task/', include('task.urls', namespace='task')),
]

task/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'task'

urlpatterns = [
    path('add/', TaskAddView.as_view(), name='task_add'),
    path('get_playbook/', get_playbook, name='get_playbook'),
    path('list/', TaskListView.as_view(), name='task_list'),
    re_path('detail/(?P<pk>[0-9]+)?/', TaskDetailView.as_view(), name='task_detail'),
    re_path('cancel/(?P<pk>[0-9]+)?/', TaskCancelView.as_view(), name='task_cancel'),
    path('get_task_result/', get_task_result, name='get_task_result'),
    re_path('publish/(?P<pk>[0-9]+)?/', task_publish, name='task_publish'),
]

templates/_paginator.html
<ul class="pagination m-b-5" style="float: right">
    {% if page_obj.has_previous %}
        <li><a href="?page=1">首页</a></li>
        <li><a href="?{{ page_obj.previous_page_number.querystring }}" aria-label="上一页">上一页</a></li>
    {% else %}
        <li><a class="disabled" href="?page=1">首页</a></li>
        <li><a class="disabled">上一页</a></li>
    {% endif %}
    {% for page in page_obj.pages %}
         {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active"><a class="">{{ page }}</a></li>
            {% else %}
                <li><a class="" href="?{{ page.querystring }}">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
             <li><a class="" href="javascript:void(0)">...</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a class="" href="?{{ page_obj.next_page_number.querystring }}">下一页</a></li>
        <li><a class="" href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
    {% else %}
        <li><a class="disabled">下一页</a></li>
        <li><a class="disabled">尾页</a></li>
    {% endif %}
</ul>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}矿场管理平台</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/ionicon/css/ionicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/helper.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
</head>

<body>
    <aside class="left-panel">
        <div class="logo">
            <a href="{% url 'cmdb:index' %}" class="logo-expanded">
                <i class="iconfont icon-Ant"></i>
                <span class="nav-label">矿场管理平台</span>
            </a>
        </div>
        <nav class="navigation">
            <ul class="list-unstyled">
                <li class="index"><a href="{% url 'cmdb:index' %}"><i class="ion-home"></i> <span
                            class="nav-label">仪表盘</span></a></li>
                <li class="has-submenu cmdb"><a href="#"><i class="fa fa-server"></i> <span
                            class="nav-label">资产管理</span></a>
                    <ul class="list-unstyled">
                        <li class="minefieldlist"><a href="{% url 'cmdb:overview' %}">资产总览</a></li>
                        <li class="storagelist"><a href="{% url 'cmdb:storagelist' %}">机器信息</a></li>
                    </ul>
                </li>
                <li class="has-submenu task"><a href="#"><i class="fa fa-tasks"></i> <span
                            class="nav-label">任务系统</span></a>
                    <ul class="list-unstyled">
                        <li class="general-task-add"><a href="{% url 'task:task_add' %}">通用任务</a></li>
                        <li class="tasks"><a href="{% url 'task:task_list' %}">任务列表</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </aside>
    <section class="content">
        <header class="top-head container-fluid">
            <button type="button" class="navbar-toggle pull-left">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <nav class=" navbar-default" role="navigation">
                <ul class="nav navbar-nav navbar-right top-menu top-right-menu">
                    <li class="dropdown text-center">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <img alt="" src="{% static 'img/avatar-2.jpg' %}" class="img-circle profile-img thumb-sm">
                            <span class="username"> {{ request.user }} </span> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pro-menu fadeInUp animated" tabindex="5003"
                            style="overflow: hidden; outline: none;">
                            <li><a href="#"><i class="fa fa-edit"></i> 修改密码</a></li>
                            <li><a href="#"><i class="fa fa-sign-out"></i> 退出</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </header>
        <div class="wraper container-fluid">
            <div class="page-title">
                <h3 class="title">{% block page-title %}{% endblock %}</h3>
            </div>
            {% block page-content %}
            {% endblock %}
        </div>
    </section>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/jquery.app.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}"></script>
    {% block js %}
    {% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
首页
{% endblock %}

{% block page-title %}
仪表盘
{% endblock %}
{% block page-content %}
<div class="row">
    <div class="col-lg-3 col-sm-6">
        <div class="widget-panel widget-style-2 white-bg">
            <i class="ion-android-social-user text-pink"></i>
            <h4 class="m-0 counter">{{ overview.task }} 个</h4>
            <div>任务总数</div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="widget-panel widget-style-2 white-bg">
            <i class="fa fa-desktop text-purple"></i>
            <h4 class="m-0 counter">{{overview.machine}} 台</h4>
            <div>资产总数</div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="widget-panel widget-style-2 white-bg">
            <i class="fa fa-tasks text-info"></i>
            <h4 class="m-0 counter">{{overview.disk}} P</h4>
            <div>硬盘容量总数</div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="widget-panel widget-style-2 white-bg">
            <i class="fa fa-tags text-success"></i>
            <h4 class="m-0 counter">{{overview.capacity}} P</h4>
            <div>可提供算力总数</div>
        </div>
    </div>
</div> <!-- end row -->
<div class="row">
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark text-uppercase">
                    算力增长
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet2"><i
                            class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet2" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <div id="user-nums" style="height:400px;"></div>
                </div>
            </div>
        </div> <!-- /Portlet -->

    </div>
    <div class="col-lg-6">
        <div class="portlet">
            <!-- /primary heading -->
            <div class="portlet-heading">
                <h3 class="portlet-title text-dark text-uppercase">
                    任务发布次数
                </h3>
                <div class="portlet-widgets">
                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                    <span class="divider"></span>
                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet1"><i
                            class="ion-minus-round"></i></a>
                    <span class="divider"></span>
                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="portlet1" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <div id="task-nums" style="height:400px;"></div>
                </div>
            </div>
        </div> <!-- /Portlet -->

    </div> <!-- end col -->

</div> <!-- End row -->


{% endblock %}
{% block js %}
<script src="/static/assets/echarts/echarts.min.js"></script>
<script src="/static/assets/echarts/theme/macarons.js"></script>
<script>
    var WorkOrderChart = echarts.init(document.getElementById('user-nums'), 'macarons');
    WorkOrderOption = {
        tooltip: {
            trigger: 'axis',
            formatter: "{b0} <br/>{a0} : {c0}"
        },
        toolbox: {
            show: true,
            feature: {
                dataZoom: { show: true },  //数据缩放
                dataView: { show: true, readOnly: true },      // 数据视图
                magicType: { show: true, type: ['line', 'bar',] }, //图形切换
                restore: { show: true },           // 数据复原
                saveAsImage: { show: true }        // 图形以图片形式保存到本地
            }
        },
        legend: {
            orient: 'horizontal',
            x: 'left',
            data: ['活跃用户数']

        },
        xAxis: {
            type: 'category',
            data: ['2019-12-02', '2019-12-03', '2019-12-04', '2019-12-05', '2019-12-06', '2019-12-07', '2019-12-08', '2019-12-09']
        },
        yAxis: {
            type: 'value'
        },
        series: [{
            name: '算力增长',
            data: [20, 22, 23, 25, 28, 33, 36, 41],
            type: 'line',
            itemStyle: {   // 系列级个性化样式，纵向渐变填充
                normal: {
                    color: '#1ab394'
                }
            },
            smooth: true
        }]
    };
    WorkOrderChart.setOption(WorkOrderOption);
</script>
<script>
    var PostChart = echarts.init(document.getElementById('task-nums'), 'macarons');
    PostOption = {
        tooltip: {
            trigger: 'axis',
            formatter: "{b0} <br/>{a0} : {c0}"

        },
        toolbox: {
            show: true,
            feature: {
                dataZoom: { show: true },  //数据缩放
                dataView: { show: true, readOnly: false },                // 数据视图
                magicType: { show: true, type: ['line', 'bar', 'tiled'] }, //图形切换
                restore: { show: true },           // 数据复原
                saveAsImage: { show: true }        // 图形以图片形式保存到本地
            }
        },
        legend: {
            orient: 'vertical',
            x: 'left',
            data: ['发布次数']

        },
        xAxis: {
            type: 'category',
            data: ['2019-12-02', '2019-12-03', '2019-12-04', '2019-12-05', '2019-12-06', '2019-12-07', '2019-12-08', '2019-12-09']
        },
        yAxis: {
            type: 'value'
        },
        series: [{
            name: '发布次数',
            data: [3, 4, 2, 5, 8, 3, 0, 6],
            type: 'bar',
            smooth: true
        }]
    };
    PostChart.setOption(PostOption);
</script>

{% endblock %}